"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var produtos_1 = require("./produtos");
var pedido_1 = require("./pedido");
var pedido = new pedido_1.Pedido();
pedido.nome = 'Pedido Geral';
var cesta1 = new pedido_1.Pedido();
cesta1.nome = "Cesta1";
var cesta2 = new pedido_1.Pedido();
cesta2.nome = "Cesta2";
var cesta3 = new pedido_1.Pedido();
cesta3.nome = "Cesta3";
var b1 = new produtos_1.Bola();
b1.valor = 31;
cesta1.addItem(b1);
var b2 = new produtos_1.Bola();
b2.valor = 32;
cesta2.addItem(b2);
var b3 = new produtos_1.Bola();
b3.valor = 33;
cesta3.addItem(b3);
var r1 = new produtos_1.Raquete();
r1.valor = 41;
cesta1.addItem(r1);
var r2 = new produtos_1.Raquete();
r2.valor = 42;
cesta2.addItem(r2);
var r3 = new produtos_1.Raquete();
r3.valor = 43;
cesta3.addItem(r3);
var bb1 = new produtos_1.BandejaBasket();
bb1.valor = 51;
cesta1.addItem(bb1);
var bb2 = new produtos_1.BandejaBasket();
bb2.valor = 52;
cesta2.addItem(bb2);
var bb3 = new produtos_1.BandejaBasket();
bb3.valor = 53;
cesta3.addItem(bb3);
pedido.addItem(cesta1);
pedido.addItem(cesta2);
pedido.addItem(cesta3);
console.log(pedido.imprimir());
